package api

func GetList() map[string]string {
	return map[string]string{
		"USD":    "US Dollar",
		"EUR":    "Euro",
		"GBP":    "British Pound",
		"BTC":    "Bitcoin",
		"ETH":    "Ethereum",
		"BCH":    "Bitcoin Cash",
		"DASH":   "Dash",
		"LTC":    "Litecoin",
		"XRP":    "Ripple",
		"XLM":    "Stellar",
		"OMG":    "OmiseGO",
		"TRX":    "TRON",
		"ADA":    "Cardano",
		"NEO":    "Neo",
		"GAS":    "Gas",
		"BAT":    "Basic Attention Token",
		"ATOM":   "Cosmos",
		"XTZ":    "Tezos",
		"ONT":    "Ontology",
		"ONG":    "Ontology Gas",
		"USDT":   "Tether",
		"USDC":   "USD Coin",
		"MATIC":  "Polygon",
		"LINK":   "Chainlink",
		"MKR":    "Maker",
		"ZRX":    "0x",
		"HOT":    "Holo",
		"DOT":    "Polkadot",
		"COMP":   "Compound",
		"ZIL":    "Zilliqa",
		"UNI":    "Uniswap",
		"UMA":    "UMA",
		"YFI":    "yearn.finance",
		"SNX":    "Synthetix",
		"KNC":    "Kyber Network",
		"BAL":    "Balancer",
		"CRV":    "Curve DAO Token",
		"WBTC":   "Wrapped Bitcoin",
		"DAI":    "Dai",
		"TUSD":   "TrueUSD",
		"SUSHI":  "SushiSwap",
		"YFII":   "DFI.money",
		"REN":    "Ren",
		"BAND":   "Band Protocol",
		"AKRO":   "Akropolis",
		"BNT":    "Bancor",
		"PAXG":   "Paxos Gold",
		"OCEAN":  "Ocean Protocol",
		"STORJ":  "Storj",
		"KAVA":   "Kava",
		"KSM":    "Kusama",
		"AAVE":   "Aave",
		"ANT":    "Aragon",
		"GLM":    "Golem",
		"TON":    "Toncoin",
		"FUN":    "FunFair",
		"UTK":    "Utrust",
		"1INCH":  "1inch",
		"INJ":    "Injective Protocol",
		"MANA":   "Decentraland",
		"LRC":    "Loopring",
		"DNT":    "district0x",
		"CVC":    "Civic",
		"XSGD":   "XSGD",
		"BNB":    "Binance Coin",
		"XVS":    "Venus",
		"TWT":    "Trust Wallet Token",
		"CAKE":   "PancakeSwap",
		"BEL":    "Bella Protocol",
		"COTI":   "COTI",
		"DOGE":   "Dogecoin",
		"ICP":    "Internet Computer",
		"JASMY":  "JasmyCoin",
		"RARI":   "Rarible",
		"SOL":    "Solana",
		"SHIB":   "Shiba Inu",
		"KP3R":   "Keep3rV1",
		"GRT":    "The Graph",
		"TRB":    "Tellor",
		"EDGT":   "Edgecoin",
		"MINA":   "Mina",
		"API3":   "API3",
		"FARM":   "Harvest Finance",
		"ARPA":   "ARPA Chain",
		"DYDX":   "dYdX",
		"SGB":    "Songbird",
		"AXS":    "Axie Infinity",
		"QRDO":   "Qredo",
		"SAND":   "The Sandbox",
		"QNT":    "Quant",
		"AVAX":   "Avalanche",
		"CRO":    "Crypto.com Coin",
		"FTM":    "Fantom",
		"APE":    "ApeCoin",
		"XDC":    "XDC Network",
		"BTTC":   "BitTorrent",
		"FIL":    "Filecoin",
		"AUDIO":  "Audius",
		"ALGO":   "Algorand",
		"EUROC":  "Euro Coin",
		"MERC":   "Mercury",
		"OP":     "Optimism",
		"LDO":    "Lido DAO",
		"GNO":    "Gnosis",
		"KEEP":   "Keep Network",
		"REQ":    "Request",
		"CHR":    "Chromia",
		"VET":    "VeChain",
		"ARV":    "Ariva",
		"ETHW":   "EthereumPoW",
		"OGN":    "Origin Protocol",
		"EOS":    "EOS",
		"BOND":   "BarnBridge",
		"LQTY":   "Liquity",
		"POLS":   "Polkastarter",
		"IDEX":   "IDEX",
		"CHZ":    "Chiliz",
		"LEVER":  "LeverFi",
		"EGLD":   "Elrond",
		"FLOW":   "Flow",
		"GBPT":   "Pound Token",
		"EURS":   "STASIS EURO",
		"IOTA":   "IOTA",
		"TXAG":   "tXAG",
		"TXAU":   "tXAU",
		"AX":     "Axie",
		"FLR":    "Flare",
		"NEAR":   "NEAR Protocol",
		"THETA":  "Theta",
		"VELO":   "Velo",
		"FET":    "Fetch.ai",
		"FIO":    "FIO Protocol",
		"APT":    "Aptos",
		"FXS":    "Frax Share",
		"ARB":    "Arbitrum",
		"CELO":   "Celo",
		"HFT":    "Hashflow",
		"ENJ":    "Enjin Coin",
		"ROSE":   "Oasis Network",
		"SC":     "Siacoin",
		"GMX":    "GMX",
		"HBAR":   "Hedera",
		"SEI":    "Sei",
		"STX":    "Stacks",
		"AGI":    "SingularityNET",
		"AI":     "Multiverse",
		"ALT":    "Alitas",
		"ANKR":   "Ankr",
		"AR":     "Arweave",
		"ARKM":   "Arkham",
		"ASM":    "Assemble Protocol",
		"BLUR":   "Blur",
		"BONK":   "Bonk",
		"CKB":    "Nervos Network",
		"IQ":     "Everipedia",
		"JUP":    "Jupiter",
		"LAI":    "LayerAI",
		"MANTA":  "Manta Network",
		"METIS":  "MetisDAO",
		"MNT":    "Mantle",
		"ONDO":   "Ondo",
		"ONE":    "Harmony",
		"ORDI":   "Ordinals",
		"PHB":    "Phoenix Global",
		"PIXEL":  "Pixel",
		"PORTAL": "Portal",
		"RNDR":   "Render Token",
		"RUNE":   "THORChain",
		"SPELL":  "Spell Token",
		"WIF":    "WiFi Map",
		"WLD":    "Worldcoin",
		"XAI":    "XAI",
		"ZETA":   "ZetaChain",
		"FLOKI":  "FLOKI",
		"MEME":   "MEME",
		"PEOPLE": "ConstitutionDAO",
		"AGIX":   "SingularityNET",
		"PEPE":   "Pepe",
		"LPT":    "Livepeer",
		"IMX":    "Immutable",
		"MASK":   "Mask Network",
		"TIA":    "TIA",
		"SUI":    "Sui",
		"XEC":    "eCash",
		"ENS":    "Ethereum Name Service",
		"QTUM":   "Qtum",
		"ETHFI":  "ETHFi",
		"BOME":   "BOMB Money",
		"ZK":     "zkSwap",
	}
}
